# Generated by Django 6.0.3 on 2026-03-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_bill_appointment_remove_bill_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='available', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='hospital.doctor')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='hospital.appointmentslot'),
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='e.g. 09:00')),
                ('end_time', models.TimeField(help_text='e.g. 13:00')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=20, help_text='Minutes per patient slot')),
                ('max_patients', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hospital.doctor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctorschedule'),
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hospital.doctor')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
